version: "3.4"

services:
  petclinic:
    image: smithst987/petclinic:latest
    container_name: petclinic
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./contrast_security.yaml:/app/petclinic/contrast_security.yaml
    environment:
      - CONTRAST_CONFIG_PATH=/app/petclinic/contrast_security.yaml
      - CONTRAST__ENABLE=TRUE
      - CONTRAST__AGENT__JAVA__STANDALONE__APP__NAME=PetClinic
      - CONTRAST__APPLICATION__GROUP=application_control_2
      - CONTRAST__APPLICATION__METADATA=bU=PS, contact=steve.smith@contrastsecurity.com
    ports:
      - "8989:8080"
