version: '3.4'

services:
  petclinic:
    environment:
      - CONTRAST__SERVER__NAME=PetClinic-qa
      - CONTRAST__SERVER__ENVIRONMENT=qa 
      - CONTRAST__ASSESS__ENABLE=true
      - CONTRAST__PROTECT__ENABLE=false
